name: 'Setup Java'
description: 'Setup requested Java version & distribution'

inputs:
  version:
    description: 'Java major version'
    default: '17'
  distribution:
    description: 'Java distribution'
    default: 'temurin'

runs:
  using: "composite"
  steps:
  - name: Set up JDK
    id: setup_jdk
    uses: actions/setup-java@v3
    with:
      java-version: ${{ inputs.version }}
      distribution: ${{ inputs.distribution }}
