// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Terra Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= terra-resource(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

terra-resource - Manage references and controlled resources in the workspace.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*terra resource* [COMMAND]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Terra contains two types of cloud resources within workspaces: *controlled* and *referenced* resources. 

A *controlled resource* is a cloud resource that is managed by Terra. Used for shared project storage and Terra-controlled analysis environments. 

A *reference* points to an *external* cloud resource that is not managed by Terra. Used for input data references, or shared cloud resources that are managed outside of Terra. 

The `check-access` command lets you see whether you have access to a particular resource. This is useful to ensure your account has access to all input data required for an analysis. 

The list of resources in a workspace is maintained on the Terra Workspace Manager server (and the CLI caches this list of resources locally). Third-party tools can access resource details via environment variables (e.g. for a resource named `mybucket`, the `$TERRA_mybucket` env variable will be populated with the bucket URL).

// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
== Commands

xref:terra-resource-add-ref.adoc[*add-ref*, *add-referenced*]::
  Add a new referenced resource.

xref:terra-resource-check-access.adoc[*check-access*]::
  Check if you have access to a referenced resource.

xref:terra-resource-create.adoc[*create*, *create-controlled*]::
  Add a new controlled resource.

xref:terra-resource-delete.adoc[*delete*]::
  Delete a resource from the workspace.

xref:terra-resource-describe.adoc[*describe*]::
  Describe a resource.

xref:terra-resource-list.adoc[*list*]::
  List all resources.

xref:terra-resource-resolve.adoc[*resolve*]::
  Resolve a resource to its cloud id or path.

xref:terra-resource-update.adoc[*update*]::
  Update the properties of a resource.

// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
