// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Terra Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= terra(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

terra - Terra command-line interface.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*terra* [COMMAND]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

The Terra CLI allows advanced users to interact with Terra workspaces and resources, and to perform administrative actions. 

== Example usage 

Fetch the user's credentials and check the authentication status. 

....

terra auth login 

terra auth status 

....

Ping the Terra server. 

....

terra server status 



....

Create a new Terra workspace and backing Google project. Check the current context to confirm it was created successfully. 

....

terra workspace create 

terra status 

....

List all workspaces the user has read or write access to. 

terra workspace list 

....

To use an existing Terra workspace, use the set command instead of create. 

....

terra workspace set --id=eb0753f9-5c45-46b3-b3b4-80b4c7bea248 

....

Create a Terra-managed bucket for temporary data storage. 

....

terra resource create gcs-bucket --name=mybucket --bucket-name=mybucket 

....



// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
== Commands

xref:terra-app.adoc[*app*]::
  Run applications in the workspace.

xref:terra-auth.adoc[*auth*]::
  Commands to manage user credentials.

xref:terra-bq.adoc[*bq*]::
  Call bq in the Terra workspace.

xref:terra-config.adoc[*config*]::
  Commands to configure the CLI.

xref:terra-gcloud.adoc[*gcloud*]::
  Call gcloud in the Terra workspace.

xref:terra-group.adoc[*group*]::
  Manage groups of Terra users.

xref:terra-gsutil.adoc[*gsutil*]::
  Call gsutil in the Terra workspace.

xref:terra-nextflow.adoc[*nextflow*]::
  Call nextflow in the Terra workspace.

xref:terra-notebook.adoc[*notebook*]::
  Use GCP Notebooks in the workspace.

xref:terra-resolve.adoc[*resolve*]::
  Resolve a resource to its cloud id or path.

xref:terra-resource.adoc[*resource*]::
  Manage references and controlled resources in the workspace.

xref:terra-server.adoc[*server*]::
  Connect to a Terra server.

xref:terra-spend.adoc[*spend*]::
  Manage spend profiles.

xref:terra-status.adoc[*status*]::
  Print details about the current workspace and server.

xref:terra-user.adoc[*user*]::
  Manage users.

xref:terra-version.adoc[*version*]::
  Get the installed version.

xref:terra-workspace.adoc[*workspace*]::
  Setup a Terra workspace.

// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
