// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Terra Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= terra-auth(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

terra-auth - Commands to manage user credentials.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*terra auth* [COMMAND]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

The Terra CLI authenticates users with the Google OAuth 2.0 installed application https://developers.google.com/identity/protocols/oauth2/native-app[flow]. 

Only one user can be logged in at a time. Call `terra auth login` to login as a different user. You don't need to login again after switching workspaces. 

You will need to login again after switching servers, because different Terra deployments may have different OAuth flows. 

By default, the CLI opens a browser window for the user to click through the OAuth flow. For some use cases (e.g. CloudShell, notebook VM), this is not practical because there is no default (or any) browser on the machine. The CLI has a browser option that controls this behavior: `terra config set browser MANUAL` means the user can copy the URL into a browser on a different machine (e.g. their laptop), complete the login prompt, and then copy/paste the response token back into the shell prompt. 



// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
== Commands

xref:terra-auth-login.adoc[*login*]::
  Authorize the CLI to access Terra APIs and data with user credentials.

xref:terra-auth-revoke.adoc[*revoke*]::
  Revoke credentials from an account.

xref:terra-auth-status.adoc[*status*]::
  Print details about the currently authorized account.

// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
