// tag::picocli-generated-full-manpage[]
// tag::picocli-generated-man-section-header[]
:doctype: manpage
:revnumber: 
:manmanual: Terra Manual
:mansource: 
:man-linkstyle: pass:[blue R < >]
= terra-resource-create-gcs-bucket(1)

// end::picocli-generated-man-section-header[]

// tag::picocli-generated-man-section-name[]
== Name

terra-resource-create-gcs-bucket - Add a controlled GCS bucket.

// end::picocli-generated-man-section-name[]

// tag::picocli-generated-man-section-synopsis[]
== Synopsis

*terra resource create gcs-bucket* [*--access*=_<access>_] *--bucket-name*=_<bucketName>_
                                 [*--cloning*=_<cloning>_]
                                 [*--description*=_<description>_]
                                 [*--format*=_<format>_] [*--location*=_<location>_]
                                 *--name*=_<name>_ [*--storage*=_<storageClass>_]
                                 [*--workspace*=_<id>_]
                                 [*--lifecycle*=_<pathToLifecycleFile>_ |
                                 *--auto-delete*=_<autoDelete>_]

// end::picocli-generated-man-section-synopsis[]

// tag::picocli-generated-man-section-description[]
== Description

Adds a controlled GCS bucket resource. 

== Lifecycle rules 

GCS bucket lifecycle rules are specified by passing a JSON-formatted file path to the `terra resource create gcs-bucket` command. 

The expected JSON structure matches the one used by the https://cloud.google.com/storage/docs/gsutil/commands/lifecycle[gsutil lifecycle command]. This structure is a subset of the https://cloud.google.com/storage/docs/json_api/v1/buckets#lifecycle[GCS resource specification]. 

There is a command shortcut for specifying a lifecycle rule which deletes any objects more than N days old: 

.... 

terra resource create gcs-bucket --name=mybucket --bucket-name=mybucket --auto-delete=365 

.... 



// end::picocli-generated-man-section-description[]

// tag::picocli-generated-man-section-options[]
== Options

*--access*=_<access>_::
  Access scope for the resource: SHARED_ACCESS, PRIVATE_ACCESS.
+
  Default: SHARED_ACCESS

*--auto-delete*=_<autoDelete>_::
  Number of days after which to auto-delete the objects in the bucket. This option is a shortcut for specifying a lifecycle rule that auto-deletes objects in the bucket after some number of days.

*--bucket-name*=_<bucketName>_::
  Name of the GCS bucket, without the prefix. (e.g. 'my-bucket', not 'gs://my-bucket').

*--cloning*=_<cloning>_::
  Instructions for handling when cloning the workspace or resource: COPY_NOTHING, COPY_DEFINITION, COPY_RESOURCE, COPY_REFERENCE.
+
  Default: COPY_NOTHING

*--description*=_<description>_::
  Description of the resource.

*--format*=_<format>_::
  Set the format for printing command output: json, text.
+
  Default: text

*--lifecycle*=_<pathToLifecycleFile>_::
  Lifecycle rules (https://cloud.google.com/storage/docs/lifecycle) specified in a JSON-formatted file. See the README for the expected JSON format.

*--location*=_<location>_::
  Bucket location (https://cloud.google.com/storage/docs/locations).
+
  Default: US-CENTRAL1

*--name*=_<name>_::
  Name of the resource, scoped to the workspace. Only alphanumeric and underscore characters are permitted.

*--storage*=_<storageClass>_::
  Storage class (https://cloud.google.com/storage/docs/storage-classes): STANDARD, NEARLINE, COLDLINE, ARCHIVE.

*--workspace*=_<id>_::
  Workspace id to use for this command only.

// end::picocli-generated-man-section-options[]

// tag::picocli-generated-man-section-arguments[]
// end::picocli-generated-man-section-arguments[]

// tag::picocli-generated-man-section-commands[]
// end::picocli-generated-man-section-commands[]

// tag::picocli-generated-man-section-exit-status[]
// end::picocli-generated-man-section-exit-status[]

// tag::picocli-generated-man-section-footer[]
// end::picocli-generated-man-section-footer[]

// end::picocli-generated-full-manpage[]
