name: Cleanup test user workspaces
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "true to do a dry run (i.e. don't actually try to delete anything), false otherwise."
        required: false
        default: 'true'
      terra_server:
        description: 'the server to cleanup (e.g. broad-dev)'
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}

jobs:
  cleanup-test-user-workspaces:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
      with:
        token: ${{ GITHUB_TOKEN }}
    - name: Setup JDK
      uses: ./.github/actions/setup_jdk
    - name: Cache Gradle packages
      uses: ./.github/actions/cache_gradle
    - name: Render config
      uses: ./.github/actions/render_config

    - name: Run cleanup script
      id: run_cleanup_script
      run: |
        echo "dryrun: $DRY_RUN"
        echo "terraserver: $TERRA_SERVER"
        if [ "$DRY_RUN" == "true" ]; then
          ./gradlew cleanupTestUserWorkspaces -Pserver=$TERRA_SERVER -PtestConfig=broad -PdryRun
        else
          ./gradlew cleanupTestUserWorkspaces -Pserver=$TERRA_SERVER -PtestConfig=broad
        fi
      env:
        DRY_RUN: ${{ github.event.inputs.dry_run }}
        TERRA_SERVER: ${{ github.event.inputs.terra_server }}
    - name: Archive logs and context file
      id: archive_logs_and_context
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: logs-and-context
        path: |
          build/test-context/.terra/logs/
          build/test-context/.terra/context.json
