name: Bump version and publish release
on:
  workflow_dispatch: {}
  push:
    branches:
      - mm-PF-569-debug-bumper-gha

jobs:
  bump-version-publish-release:
    runs-on: ubuntu-latest
    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
      - name: Checkout current code
        uses: actions/checkout@v2
        with:
          ref: mm-PF-569-debug-bumper-gha
      - name: Bump tag and build version
        uses: databiosphere/github-actions/actions/bumper@v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: mm-PF-569-debug-bumper-gha
          VERSION_FILE_PATH: build.gradle
          VERSION_LINE_MATCH: ^version
      - name: Publish a release
        run: |
          echo "TODO (PF-570): ./tools/publish-release.sh $RELEASE_VERSION true"
        env:
          GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
