name: Run tests against PRs (pre and post merge)
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-static-analysis:
    runs-on: ubuntu-latest
    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
      - name: Checkout current code
        id: checkout_code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
          ref: main
      - name: Run linter
        id: run_linter
        run: |
          ./gradlew spotlessCheck
      - name: Run static analysis
        id: run_static_analysis
        run: |
          ./gradlew spotbugsMain spotbugsTest
