name: Publish Release
on:
  workflow_dispatch: {}
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello 123!"
          echo "- in 234!"
