name: Publish Release
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
      - name: Checkout current code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: "Bump the tag to a new version"
#        uses: databiosphere/github-actions/actions/bumper@v0.0.3
#        env:
#          GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
#          RELEASE_BRANCHES: main
#          VERSION_FILE_PATH: build.gradle
#          VERSION_LINE_MATCH: ^version
      - name: Publish a release
        run: |
          echo "pwd: $PWD"
          echo "home: $HOME"
          ls -la
          ls -la /usr/bin/g*
          gh release list
#          tools/publish-release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG_NAME: ${{ 0.0 }}
