name: Bump version and publish release
on:
  workflow_dispatch: { }
  push:
    branches: [ main ]
    paths-ignore: [ '**.md' ]

env:
  GITHUB_TOKEN: ${{ secrets.BROADBOT_GITHUB_TOKEN }}

jobs:
  bump-version-publish-release:
    runs-on: ubuntu-latest
    if: "!contains( github.event.sender.login, 'broadbot')"
    steps:
    - name: Checkout current code
      uses: actions/checkout@v2
      with:
        token: ${{ GITHUB_TOKEN }}
        ref: main
    - name: Setup JDK
      uses: ./.github/actions/setup_jdk

    - name: Bump tag and build version
      id: bump_tag
      uses: databiosphere/github-actions/actions/bumper@bumper-0.0.6
      env:
        GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
        DEFAULT_BUMP: minor
        RELEASE_BRANCHES: main
        VERSION_FILE_PATH: build.gradle
        VERSION_LINE_MATCH: ^version\>
    - name: Updating code to get the version bump changes
      id: update_code_post_version_bump
      run: |
        git pull
      env:
        GITHUB_TOKEN: ${{ GITHUB_TOKEN }}

    - name: Render config
      uses: ./.github/actions/render_config

    - name: Publish a release
      run: |
        ./tools/publish-release.sh $RELEASE_VERSION true
      env:
        GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ steps.bump_tag.outputs.tag }}
