name: Run tests nightly
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * *' # 5AM UTC = 12AM EST

jobs:
  tests-against-source-code-and-latest-install:
    strategy:
      matrix:
        testOptions: [ "-PtestTag=unit", "-PtestTag=integration", "-PtestTag=integration -PtestInstallFromGitHub" ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        id: checkout_code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
      - name: Set up AdoptOpenJDK 11
        id: setup_jdk
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11
      - name: Cache Gradle packages
        id: cache_gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Grant execute permission for gradlew
        id: allow_execute_gradle
        run: chmod +x gradlew
      - name: Render config
        id: render_config
        run: |
          # this step does the equivalent of the tools/render-config.sh script.
          # on local machines, the script fetches a SA from Vault.
          # in GH actions, the SA key is stored in a GH repo secret.
          # regardless of how it was fetched, tests expect these
          # keys to be stored in rendered/
          mkdir -p rendered
          echo "$TEST_USER_SA_KEY" > rendered/test-user-account.json
          echo "$DEV_CI_SA_KEY" > rendered/ci-account.json
        env:
          TEST_USER_SA_KEY: ${{ secrets.TEST_USER_SA_KEY }}
          DEV_CI_SA_KEY: ${{ secrets.DEV_CI_SA_KEY }}
      - name: Run tests
        id: run_tests
        run: |
          # runs against the default server: terra-dev
          echo "Running tests with options: ${{ matrix.testOptions }}"
          ./gradlew runTestsWithTag ${{ matrix.testOptions }}
      - name: Archive logs and context file
        id: archive_logs_and_context
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs-and-context-[${{ matrix.testOptions }}]
          path: |
            build/test-context/.terra/logs/
            build/test-context/.terra/global-context.json
      - name: Notify PF alerts slack channel
        # don't notify manually triggered runs
        if: always() && github.event_name == 'workflow_dispatch'
        uses: broadinstitute/action-slack@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: ${{ job.status }}
          channel: "@mmedlock" #"#platform-foundation-alerts"
          username: "CLI nightly test run"
          icon_emoji: ":cli:"
          fields: repo,commit,job,took
