name: Run tests nightly
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 5 * * *' # 5AM UTC = 12AM EST

jobs:
  tests-against-source-code-and-latest-install:
    strategy:
      matrix:
        testServer: [ "broad-dev" ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current code
        id: checkout_code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
      - name: Set up AdoptOpenJDK 11
        id: setup_jdk
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11
      - name: Cache Gradle packages
        id: cache_gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
      - name: Render config
        id: render_config
        run: |
          # For security reasons, Broad prefers we read GHA secrets instead of reading from vault.
          # this step does the equivalent of the tools/render-config.sh script.
          # on local machines, the script fetches a SA from Vault.
          # in GH actions, the SA key is stored in a GH repo secret.
          # regardless of how it was fetched, tests and scripts expect these
          # keys to be stored in rendered/broad/
          mkdir -p rendered/broad/
          echo "$TEST_USER_SA_KEY" > rendered/broad/test-user-account.json
          echo "$EXT_PROJECT_SA_KEY" > rendered/broad/external-project-account.json
          echo "$JANITOR_CLIENT_SA_KEY" > rendered/broad/janitor-client.json
          echo "$BROOKLYN_THUNDERLORD" > rendered/broad/Brooklyn.Thunderlord@test.firecloud.org.json
          echo "$ETHAN_BONECHEWER" > rendered/broad/Ethan.Bonechewer@test.firecloud.org.json
          echo "$JOHN_WHITECLAW" > rendered/broad/John.Whiteclaw@test.firecloud.org.json
          echo "$LILY_SHADOWMOON" > rendered/broad/Lily.Shadowmoon@test.firecloud.org.json
          echo "$NOAH_FROSTWOLF" > rendered/broad/Noah.Frostwolf@test.firecloud.org.json
          echo "$PENELOPE_TWILIGHTSHAMMER" > rendered/broad/Penelope.TwilightsHammer@test.firecloud.org.json
        env:
          TEST_USER_SA_KEY: ${{ secrets.TEST_USER_SA_KEY }}
          EXT_PROJECT_SA_KEY: ${{ secrets.EXT_PROJECT_SA_KEY }}
          JANITOR_CLIENT_SA_KEY: ${{ secrets.JANITOR_CLIENT_SA_KEY }}
          BROOKLYN_THUNDERLORD: ${{ secrets.BROOKLYN_THUNDERLORD }}
          ETHAN_BONECHEWER: ${{ secrets.ETHAN_BONECHEWER }}
          JOHN_WHITECLAW: ${{ secrets.JOHN_WHITECLAW }}
          LILY_SHADOWMOON: ${{ secrets.LILY_SHADOWMOON }}
          NOAH_FROSTWOLF: ${{ secrets.NOAH_FROSTWOLF }}
          PENELOPE_TWILIGHTSHAMMER: ${{ secrets.PENELOPE_TWILIGHTSHAMMER }}
      - name: Run unit tests
        id: run_unit_tests
        if: always()
        run: |
          echo "Running unit tests for server: ${{ matrix.testServer }}"
          mkdir -p ~/logs-unit
          ./gradlew runTestsWithTag -PtestTag=unit --scan -Pserver=${{ matrix.testServer }} -PcontextDir=$HOME/logs-unit
      - name: Run integration tests against source code
        id: run_integration_tests_against_source_code
        if: always()
        run: |
          echo "Running integration tests against source code for server: ${{ matrix.testServer }}"
          mkdir -p ~/logs-integration-source
          ./gradlew runTestsWithTag -PtestTag=integration --scan -Pserver=${{ matrix.testServer }} -PcontextDir=$HOME/logs-integration-source
      - name: Run integration tests against release
        id: run_integration_tests_against_release
        if: always()
        run: |
          echo "Running integration tests against release for server: ${{ matrix.testServer }}"
          mkdir -p ~/logs-integration-release
          ./gradlew runTestsWithTag -PtestTag=integration --scan -PtestInstallFromGitHub -Pserver=${{ matrix.testServer }} -PcontextDir=$HOME/logs-integration-release
      - name: Compile logs and context files for all test runs
        id: compile_logs_and_context_files
        if: always()
        run: |
          declare -a arr=("unit" "integration-source" "integration-release")
          for i in "${arr[@]}"
          do
            echo "Compiling logs and context files for test run: $i"
            mkdir -p ~/to-archive/$i
            cp -R ~/logs-$i/.terra/logs/ ~/to-archive/$i/logs/
            cp -R ~/logs-$i/.terra/context.json ~/to-archive/$i/context.json
          done
      - name: Archive logs and context file for all test runs
        id: archive_logs_and_context
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs-and-context-${{ matrix.testServer }}
          path: |
            ~/to-archive/
      - name: Compose status message
        id: compose_status_message
        if: always()
        run: |
          title="CLI nightly test run: ${{ matrix.testServer }}"
          L2="Unit: ${{ steps.run_unit_tests.outcome }} "
          L3="Integ (Source): ${{ steps.run_integration_tests_against_source_code.outcome }} "
          L4="Integ (Release): ${{ steps.run_integration_tests_against_release.outcome }}"
          bold="$L2 | $L3 | $L4"
          text="Link to <https://github.com/DataBiosphere/terra-cli/actions/runs/$GITHUB_RUN_ID|test run>"
          if [ "${{ job.status }}" == "success" ]; then
            text=":white_check_mark: $text"
          else
            text=":no_entry: $text"
          fi
          echo ::set-output name=status-title::$title
          echo ::set-output name=status-bold::$bold
          echo ::set-output name=status-text::$text
      - name: Notify PF alerts slack channel
        # don't notify manually triggered runs
        if: always() && github.event_name != 'workflow_dispatch'
        uses: broadinstitute/action-slack@v3.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        with:
          status: ${{ job.status }}
          channel: "#platform-foundation-alerts"
          username: ${{ steps.compose_status_message.outputs.status-title }}
          author_name: ${{ steps.compose_status_message.outputs.status-bold }}
          icon_emoji: ':cli:'
          text: ${{ steps.compose_status_message.outputs.status-text }}
