# This is a manual-trigger-only Github action for updating gradle version.
# A gradle version such as 7.1.5 needs to be passed in to run this action. A
# PR will be generated. If tests fail, the PR will need human intervention. You
# can checkout the branch and make more changes and commit again. Doing so,
# your manual fix is separated from the generated code, making it easier for
# the reviewers to know what to look at.
name: Update gradlew version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The gradlew version to upgrade to'
        required: true

jobs:
  update-gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout current code
      id: checkout_code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Update Gradle wrapper
      run: ./gradlew wrapper --gradle-version ${{ github.event.inputs.version }}
    - name: create PR
      id: create-pr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.BROADBOT_GITHUB_TOKEN }}
        commit-message: "Terra CLI gradlew update to ${{ github.event.inputs.version }}"
        committer: terracli-bot <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        title: "Terra CLI gradlew update version to ${{ github.event.inputs.version }}"
        branch: "actions/update-gradlew"
        delete-branch: true
        body: |
          Update gradlew version.
          *Note: This PR was opened by the [update-gradle-version GitHub Actions workflow](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).*
